services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/web-service:latest
    ports:
      - "8001:8001"
    environment:
      - LISTEN_PORT=8001
  web2:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/web-service:latest
    ports:
      - "8002:8002"
    environment:
      - LISTEN_PORT=8002
  web3:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/web-service:latest
    ports:
      - "8003:8003"
    environment:
      - LISTEN_PORT=8003

  haproxy:
    image: haproxy:latest
    ports:
      - "8088:8080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web1
      - web2
      - web3